version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.11.0


jobs:
  test-and-build:
    docker:
      - image: circleci/node:13.12.0
    steps:
      - checkout 
      - run: npm install
      - run: npm run test 
        
workflows:
  build-project:
    jobs:
      - test-and-build
      - gcp-gcr/build-and-push-image:
          context: GCP
          image: my-image
          registry-url: eu.gcr.io
          requires:
            - test-and-build